In [4]:
import numpy as np
import pandas as pd

In [17]:
array = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [0,0,0]]])

In [18]:
print(array)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 0 0]]]


In [19]:
print('#dim:', array.ndim)
print('shape:', array.shape)
print('size:', array.size)

#dim: 3
shape: (2, 2, 3)
size: 12


In [24]:
a1 = np.array([1,2,3], dtype=np.int)
print(a1.dtype)

int32


In [25]:
a2 = np.arange(12)
print(a2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [27]:
a2 = a2.reshape(6,2)
print(a2)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [28]:
a3 = np.linspace(0,10,5)
print(a3)

[ 0.   2.5  5.   7.5 10. ]


In [29]:
s = pd.Series([1,3,6,np.nan,44,1])
s

0     1.0
1     3.0
2     6.0
3     NaN
4    44.0
5     1.0
dtype: float64

In [36]:
dates = pd.date_range('20181208', periods=6)
dates

DatetimeIndex(['2018-12-08', '2018-12-09', '2018-12-10', '2018-12-11',
               '2018-12-12', '2018-12-13'],
              dtype='datetime64[ns]', freq='D')

In [38]:
df = pd.DataFrame(np.arange(24).reshape(6,4), index=dates, columns=['a','b','c','d'])
df

a   b   c   d
2018-12-08   0   1   2   3
2018-12-09   4   5   6   7
2018-12-10   8   9  10  11
2018-12-11  12  13  14  15
2018-12-12  16  17  18  19
2018-12-13  20  21  22  23

In [43]:
print(df['a'], '\n' ,df.a)
# same

2018-12-08     0
2018-12-09     4
2018-12-10     8
2018-12-11    12
2018-12-12    16
2018-12-13    20
Freq: D, Name: a, dtype: int32 
 2018-12-08     0
2018-12-09     4
2018-12-10     8
2018-12-11    12
2018-12-12    16
2018-12-13    20
Freq: D, Name: a, dtype: int32


In [46]:
print(df[0:-2])

             a   b   c   d
2018-12-08   0   1   2   3
2018-12-09   4   5   6   7
2018-12-10   8   9  10  11
2018-12-11  12  13  14  15


In [47]:
print(df['20181208':'20181210'])

            a  b   c   d
2018-12-08  0  1   2   3
2018-12-09  4  5   6   7
2018-12-10  8  9  10  11


In [48]:
# select by label
print(df.loc['20181209'])

a    4
b    5
c    6
d    7
Name: 2018-12-09 00:00:00, dtype: int32


In [49]:
print(df.loc['20181208',['b','c']])

b    1
c    2
Name: 2018-12-08 00:00:00, dtype: int32


In [56]:
# select by position
print(df.iloc[3])
print(df.iloc[3,3])
print(df.iloc[1:3,0:2])
print(df.iloc[[1,3,5],0:2])

a    12
b    13
c    14
d    15
Name: 2018-12-11 00:00:00, dtype: int32
15
            a  b
2018-12-09  4  5
2018-12-10  8  9
             a   b
2018-12-09   4   5
2018-12-11  12  13
2018-12-13  20  21
